### ISSUE TITLE
Request: requirements.txt

### ISSUE THREAD

**Issue by franzmaliszt** [ENHANCE-PET/nifti2dicom#29]
Hello, thanks for putting this out there.

I was able to run a multilable segmentation conversion without any runtime problem. However, i noticed the issue in title when i tested it with eye.
nifti2dicom is not probably the direct cause. It looks like a floating point precision issue, that happens in one of the dependent libraries.
I back this further by my experience building nifti2dicom. Lack of a requirements.txt with **pinned versions** required me to play with dependency versions. I failed with python 3.11.

#27 did not completely fix the issue. Released version 1.2.4 does not have it.

This project can really use more deterministic builds. Logs in build actions are not there anymore, so i was not able to find the actual versions of dependencies.
I would appreciate it a lot, if you can add a requirements.txt

Thanks

**Comment by LalithShiyam** [comment]
Hi @franzmaliszt, Truly sorry about the delay. I was traveling. I understand your frustration. But the requirements are already in the setup.py?

**Comment by franzmaliszt** [comment]
All good, this project is worth waiting, thanks a lot again.

It is true that `setup.py` includes the requirements, though it also requires `simpleitk` for segmentation conversion.
However, as the dependent packages release new versions, the versions pulled by pip to build `nifti2dicom` changes. Having them pinned would let users in the future know about working set of dependencies.

As i dug deeper to follow the problem, i realized [highdicom not supporting pydicom 3](https://github.com/ImagingDataCommons/highdicom/pull/301) might be the cause.
I will try building `nifti2dicom` again with after new release of `highdicom`. 

In the end i had to create this `requirements.txt` only to install `nifti2dicom`:
```
nifti2dicom==1.2.4
pydicom==2.4.4
simpleitk==2.4.0
numpy<2.0.0
```
This builds, but results in a slight overlapping issue i mentioned.

Can i kindly ask if you are able to build nifti2dicom from source now, without any dependency problem?

**Comment by LalithShiyam** [comment]
It's definitely pydicom==3.0, it pretty much broke our entire stack. So we went for pydicom<3.0 in our setup.py. And it works now...

**Comment by franzmaliszt** [comment]
I see. I went `pydicom<3.0.0` to install highdicom. So if im not mistaken, the fix will come from there.

Note that highdicom will require python 3.10 or higher with that release, [source](https://github.com/ImagingDataCommons/highdicom/issues/300#issuecomment-2351692304). In that case, prerequisite for this package will need to be updated.

**Comment by LalithShiyam** [comment]
You are wonderful - many thanks! will do that now.

**Comment by franzmaliszt** [comment]
highdicom has released the [version](https://github.com/ImagingDataCommons/highdicom/releases/tag/v0.23.0), and it requires pydicom 3.
This conflicts with `nifti2dicom` requiring `pydicom<3`, so pip can not install the new highdicom version.
What broke your stack might have been highdicom. It was the reason i could not just do `pip install nifti2dicom` in the first place. If this is the case, you might need to revert your fix.

Aside all that, `simpleitk` is a requirement that is not listed in the setup.py.

**Comment by LalithShiyam** [comment]
Please bear with me for a couple of days. We have some high pressure deadlines. And we are pretty much saturated. I will get this sorted as soon as possible. Also, if you have sorted it, feel free to make a PR. Happy to merge. 

Truly sorry. Just bad timing from my side.

**Comment by franzmaliszt** [comment]
Kind reminder that this package needs to release to fix the latest version on pypi. I'm still able to build from source, though.

The issue title is also misleading and i guess it can be closed after new release. I will investigate further on segmentation overlap issue i mentioned. I expect it to go away, but lets see.

Also, thanks for the shoutout!

**Comment by LalithShiyam** [comment]
@franzmaliszt thanks for the reminder :) `nifti2dicom 1.2.6` is live and thanks for your contribution!

**Comment by LalithShiyam** [comment]
@franzmaliszt if everything works, may I close this?

**Comment by franzmaliszt** [comment]
Yes, looks good

**Comment by LalithShiyam** [comment]
@franzmaliszt fantastic, thanks for your help again!
